version: '2'
services:
    springlegacy-app:
        image: springlegacy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://springlegacy-mysql:3306/springlegacy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    springlegacy-mysql:
        extends:
            file: mysql.yml
            service: springlegacy-mysql
